### ISSUE TITLE
Inline 

### ISSUE THREAD

**Issue by holtgrewe** [nyergler/hieroglyph#112]
I have a problem with the `inlineslides` slide builder (both with the latest release and when building directly from Githbub). Please advice.

```
# sphinx-build -b inlineslides -d build/doctrees   source build/slides
...
Exception occurred:
  File ".../.venv/lib/python3.4/site-packages/sphinx/jinja2glue.py", line 159, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: slide.html
The full traceback has been saved in /tmp/sphinx-err-fkxkqacf.log, if you want to report the issue to the developers.
```

**Comment by holtgrewe** [comment]
Here is the content of the log file, btw

```
# Sphinx version: 1.3.3
# Python version: 3.4.3 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [ 50%] index
#   writing output... [100%] introduction
# Loaded extensions:
#   hieroglyph (unknown version) from /home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/hieroglyph/__init__.py
#   alabaster (0.7.7) from /home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/alabaster/__init__.py
#   sphinx.ext.mathjax (1.3.3) from /home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/sphinx/ext/mathjax.py
Traceback (most recent call last):
  File "/home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/sphinx/cmdline.py", line 240, in main
    app.build(opts.force_all, filenames)
  File "/home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/sphinx/application.py", line 266, in build
    self.builder.build_update()
  File "/home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 252, in build_update
    'out of date' % len(to_build))
  File "/home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 323, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 361, in write
    self._write_serial(sorted(docnames), warnings)
  File "/home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/sphinx/builders/__init__.py", line 369, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/sphinx/builders/html.py", line 439, in write_doc
    self.docwriter.write(doctree, destination)
  File "/home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/sphinx/writers/html.py", line 53, in translate
    self.document.walkabout(visitor)
  File "/home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/docutils/nodes.py", line 187, in walkabout
    visitor.dispatch_departure(self)
  File "/home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/docutils/nodes.py", line 1895, in dispatch_departure
    return method(node)
  File "/home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/hieroglyph/writer.py", line 224, in depart_slide
    self.current_slide.get_slide_context(),
  File "/home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/sphinx/jinja2glue.py", line 138, in render
    return self.environment.get_template(template).render(context)
  File "/home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/home/mholtgre/Development/snakemake_tutorial/.venv/lib/python3.4/site-packages/sphinx/jinja2glue.py", line 159, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: slide.html
```
