### ISSUE TITLE
"make slides" stalls on "reading sources... [100%] index"

### ISSUE THREAD

**Issue by arthurlogilab** [nyergler/hieroglyph#131]
```
$ make slides
Running Sphinx v1.6.3
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [slides]: targets for 1 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
^Cading sources... [100%] index                                                                       
interrupted!
Makefile:20: recipe for target 'slides' failed
make: *** [slides] Interrupt
```

it blocks on "reading sources" (then I did ctrl-C)

With added verbosity I get : 

```
[snip]
0 added, 1 changed, 0 removed
[app] emitting event: 'env-before-read-docs'(<sphinx.environment.BuildEnvironment object at 0x7f945f235c50>, ['index'])
reading sources... [100%] index
[app] emitting event: 'env-purge-doc'(<sphinx.environment.BuildEnvironment object at 0x7f945f235c50>, 'index')
[app] emitting event: 'source-read'('index', [".. QA documentation master file, created by\n   sphinx-quickstart on Tue Sep 26 15:56:54
^C
Traceback (most recent call last):
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 331, in build_update
    'out of date' % len(to_build))
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 344, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 583, in update
    self._read_serial(docnames, self.app)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 602, in _read_serial
    self.read_doc(docname, app)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/sphinx/environment/__init__.py", line 723, in read_doc
    pub.publish()
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/sphinx/io.py", line 74, in read
    self.parse()
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/parsers/rst/__init__.py", line 191, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2328, in explicit_markup
    self.explicit_list(blank_finish)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2358, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 312, in nested_list_parse
    **state_machine_kwargs)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/statemachine.py", line 167, in __init__
    self.add_states(state_classes)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/statemachine.py", line 485, in add_states
    self.add_state(state_class)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/statemachine.py", line 478, in add_state
    self.states[statename] = state_class(self, self.debug)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 216, in __init__
    StateWS.__init__(self, state_machine, debug)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/statemachine.py", line 963, in __init__
    State.__init__(self, state_machine, debug)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/statemachine.py", line 620, in __init__
    self.add_initial_transitions()
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/statemachine.py", line 979, in add_initial_transitions
    State.add_initial_transitions(self)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/statemachine.py", line 649, in add_initial_transitions
    self.initial_transitions)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/statemachine.py", line 745, in make_transitions
    transitions[namestate[0]] = self.make_transition(*namestate)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/site-packages/docutils/statemachine.py", line 718, in make_transition
    pattern = re.compile(pattern)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/re.py", line 224, in compile
    return _compile(pattern, flags)
  File "/home/arthur/.virtualenvs/formation/lib/python3.5/re.py", line 281, in _compile
    p, loc = _cache[type(pattern), pattern, flags]
KeyboardInterrupt

interrupted!

```

**Comment by arthurlogilab** [comment]
Found it... I had a loop in the includes. (a job for doc8 checker or rst-lint I guess) 

Using ```for i in `ls *.rst` ; do echo .. include:: $i; done ``` and including index.rst is not a good idea.
