### ISSUE TITLE
No module named 'sphinx.quickstart'

### ISSUE THREAD

**Issue by yves-chevallier** [nyergler/hieroglyph#165]
It seems `sphinx.quickstart` does not exists in Sphinx 2 and has been renamed `sphinx.cmd.quickstart`. 

```
$ hieroglyph-quickstart
Traceback (most recent call last):
  File "/usr/local/bin/hieroglyph-quickstart", line 7, in <module>
    from hieroglyph.quickstart import quickstart
  File "/usr/local/lib/python3.6/dist-packages/hieroglyph/quickstart.py", line 1
0, in <module>
    import sphinx.quickstart
ModuleNotFoundError: No module named 'sphinx.quickstart'
```

But even renaming `sphinx.quickstart` with `sphinx.cmd.quickstart` I still get an error:

```
$ hieroglyph-quickstart
Traceback (most recent call last):
  File "/usr/local/bin/hieroglyph-quickstart", line 11, in <module>
    sys.exit(quickstart())
  File "/usr/local/lib/python3.6/dist-packages/hieroglyph/quickstart.py", line 87, in quickstart
    d = sphinx.cmd.quickstart.DEFAULT_VALUE.copy()
AttributeError: module 'sphinx.cmd.quickstart' has no attribute 'DEFAULT_VALUE'
```

I do have this version of sphinx:

```
$ sphinx-quickstart --version
sphinx-quickstart 2.1.2
```

**Comment by yves-chevallier** [comment]
Well it seems it works with the current branch: pip install git+https://github.com/nyergler/hieroglyph#egg=hieroglyph
