### ISSUE TITLE
Support for plantuml on slides

### ISSUE THREAD

**Issue by SteinHeselmans** [nyergler/hieroglyph#168]
Plantuml is a nice tool to draw uml diagrams from text, i use it often in html/pdf docs. On slides (using hieroglyph) it would be nice as well, but it doesn't work. I'm not sure whether it is an error in the hieroglyph, or the plantuml plugin. Feel free to move, if i made the wrong assumption...

The plantuml plugin: https://pypi.org/project/sphinxcontrib-plantuml/

I get this error:

> Exception occurred:
>   File "/usr/local/lib/python3.6/dist-packages/sphinx/writers/html.py", line 833, in unknown_visit
>     raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
> NotImplementedError: Unknown node: plantuml

The log-file shows:

```
# Sphinx version: 2.4.4
# Python version: 3.6.9 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.10
# Last messages:
#   checking consistency...
#   
#   done
#   
#   preparing documents...
#   
#   done
#   
#   writing output... [ 50%] csop-destination-mac
#   
# Loaded extensions:
#   sphinx.ext.mathjax (2.4.4) from /usr/local/lib/python3.6/dist-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/local/lib/python3.6/dist-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/local/lib/python3.6/dist-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /usr/local/lib/python3.6/dist-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /usr/local/lib/python3.6/dist-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/local/lib/python3.6/dist-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/local/lib/python3.6/dist-packages/alabaster/__init__.py
#   hieroglyph (unknown version) from /usr/local/lib/python3.6/dist-packages/hieroglyph/__init__.py
#   sphinxcontrib.plantuml (unknown version) from /usr/local/lib/python3.6/dist-packages/sphinxcontrib/plantuml.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/application.py", line 349, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.6/dist-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/usr/local/lib/python3.6/dist-packages/sphinx/builders/__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/builders/__init__.py", line 535, in write
    self._write_serial(sorted(docnames))
  File "/usr/local/lib/python3.6/dist-packages/sphinx/builders/__init__.py", line 545, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/local/lib/python3.6/dist-packages/hieroglyph/builder.py", line 137, in write_doc
    result = super(AbstractSlideBuilder, self).write_doc(docname, doctree)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/builders/html.py", line 612, in write_doc
    self.docwriter.write(doctree, destination)
  File "/usr/local/lib/python3.6/dist-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/local/lib/python3.6/dist-packages/sphinx/writers/html.py", line 58, in translate
    self.document.walkabout(visitor)
  File "/usr/local/lib/python3.6/dist-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python3.6/dist-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python3.6/dist-packages/docutils/nodes.py", line 206, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/util/docutils.py", line 486, in dispatch_visit
    super().dispatch_visit(node)
  File "/usr/local/lib/python3.6/dist-packages/docutils/nodes.py", line 1995, in dispatch_visit
    return method(node)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/writers/html.py", line 833, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: plantuml

```

**Comment by nyergler** [comment]
I'm pretty sure this the same as or at least closely related to #148

**Comment by nyergler** [comment]
This should be fixed on `master` now, @SteinHeselmans. If you're able to test with `master`, that'd be appreciated.

**Comment by SteinHeselmans** [comment]
@nyergler , tested on master: that works! Thanks for fixing it. Could you push a new version to pypi?

**Comment by nyergler** [comment]
I just pushed Hieroglyph 2.1.0 to PyPI. Thanks for your help!
