### ISSUE TITLE
Behaviour of rst-class:: build

### ISSUE THREAD

**Issue by AndreaCrotti** [nyergler/hieroglyph#17]
I don't understand how rst-class:: build should be used to produce smarter slides..

For examples if I do this:

    .. rst-class:: build
    
    ::
       
        Traceback (most recent call last):
          File "funcs.py", line 45, in <module>
            test_smart()
          File "/home/andrea/.local/lib/python2.7/site-packages/mock.py", line 1224, in patched
            return func(*args, **keywargs)
          File "funcs.py", line 24, in test_smart
            smart_function(100)
          File "funcs.py", line 17, in smart_function
            report_error(argO)
        NameError: global name 'argO' is not defined
    
    .. literalinclude:: code/funcs.py
        :pyobject: smart_function
    

It will first show the code included below, and then the traceback on
top, but other times it seems to go in order.

Is that desired behaviour? Or what is the rule in general to understand how to use this?

Thanks a lot!

**Comment by nyergler** [comment]
I don't think there's anything to do here. Closing.
